name: Push Container to Heroku

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        if: github.ref == 'refs/heads/develop' && job.status == 'success'
        run: git subtree push --prefix BE https://heroku:$HEROKU_API_TOKEN@git.heroku.com/codesqaud-team1-sign-up.git master
